name: Run Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    services:
      docker:
        image: docker:19.03.12  # Specify a Docker image for Docker setup
        options: --privileged  # Allow privileged mode for Docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out your repository code

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for multi-platform builds

    - name: Build Docker container
      run: |
        docker build -t my-app .  # Build your Docker image

    - name: Run app in Docker container
      run: |
        docker run -d --name my-app-container my-app  # Run the app inside the container

    - name: Install dependencies inside Docker container
      run: |
        docker exec my-app-container pip install -r dependencies.txt  # Install any Python dependencies

    - name: Run tests inside Docker container
      run: |
        docker exec my-app-container python -m unittest test-api.py  # Run the tests inside the container

    - name: Stop and remove Docker container
      run: |
        docker rm -f my-app-container  # Clean up by stopping and removing the container
